import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Div } from "./Components";
import { SearchProvider } from "./context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eatly App By Muzaffar Kholikov",
  description: "Generated by next app by Muzaffar Kholikov",
  keywords:
    "Najot Talim, najottalim, Uzb, Zomin, Tashkent, Jizzax, Muzaffar Kholikov, next, Exam, Portfolio, Zerikdim, next proyekt, next Portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SearchProvider>
        <body className={inter.className}>
          <Div className="select-none main container mx-auto flex flex-col justify-between bg-[#F9F9F9]">
            {children}
          </Div>
        </body>
      </SearchProvider>
    </html>
  );
}
